[workspace]
members = [
	"crates/dm-conformance",
	"crates/dm-compiler",
	"crates/dm-core",
	"crates/dm-lexer",
	"crates/dm-object-tree",
	"crates/dm-project",
	"crates/dm-semantics",
	"crates/dm-syntax",
	"crates/dm-vm",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.85"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
