[package]
name = "dm-compiler"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
dm-core = { path = "../dm-core" }
dm-lexer = { path = "../dm-lexer" }
dm-object-tree = { path = "../dm-object-tree" }
dm-project = { path = "../dm-project" }
dm-syntax = { path = "../dm-syntax" }
md5 = "0.7"

[lints]
workspace = true
