[package]
name = "dm-conformance"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
dm-compiler = { path = "../dm-compiler" }
dm-lexer = { path = "../dm-lexer" }
dm-project = { path = "../dm-project" }
dm-syntax = { path = "../dm-syntax" }
dm-value = { path = "../dm-value" }
dm-vm = { path = "../dm-vm" }

[lints]
workspace = true
