[package]
name = "dm-world"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
dm-compiler = { path = "../dm-compiler" }
dm-core = { path = "../dm-core" }
dm-globals = { path = "../dm-globals" }
dm-map = { path = "../dm-map" }
dm-object-tree = { path = "../dm-object-tree" }
dm-runtime = { path = "../dm-runtime" }
dm-value = { path = "../dm-value" }
dm-vm = { path = "../dm-vm" }

[lints]
workspace = true
