[workspace]

[package]
name = "dm-lifecycle"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"
publish = false

[dependencies]
dm-compiler = { path = "../dm-compiler" }
dm-core = { path = "../dm-core" }
dm-map = { path = "../dm-map" }
dm-object-tree = { path = "../dm-object-tree" }
dm-runtime = { path = "../dm-runtime" }
dm-semantics = { path = "../dm-semantics" }
dm-world = { path = "../dm-world" }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
