[package]
name = "dm-lifecycle"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"
publish = false
autobins = false

[[bin]]
name = "dream64-server"
path = "src/main.rs"

[[bin]]
name = "dream64-compiler"
path = "src/bin/dream64-compiler.rs"

[dependencies]
crc32fast = "1.5"
dm-compiler = { path = "../dm-compiler" }
dm-core = { path = "../dm-core" }
dm-map = { path = "../dm-map" }
dm-mmap = { path = "../dm-mmap" }
dm-object-tree = { path = "../dm-object-tree" }
dm-project = { path = "../dm-project" }
dm-runtime = { path = "../dm-runtime" }
dm-semantics = { path = "../dm-semantics" }
dm-value = { path = "../dm-value" }
dm-vm = { path = "../dm-vm" }
dm-world = { path = "../dm-world" }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
md5 = "0.7"

[build-dependencies]
md5 = "0.7"

[dev-dependencies]
md5 = "0.7"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
