[package]
name = "dm-lowering"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
dm-compiler = { path = "../dm-compiler" }
dm-core = { path = "../dm-core" }
dm-semantics = { path = "../dm-semantics" }
dm-vm = { path = "../dm-vm" }

[lints]
workspace = true
